This will disable FastMuxSwitch if a client is actively transcoding a liveTV stream.
google/sagetv pull request #448
Opened 2021-03-31 17:05 UTC by jvl711

It appears that when SageTV is doing server side transcoding that it is not able to do a fastmuxswitch and have the client transition to the new program/timeslot.  I have noticed this behavior in the Placeshifter, and the andriod client.  With this change, placeshifter is able to transition between timeslots without issue.  And when you are using a client without transcoding, it does a fastmuxswitch without issue.

2021-03-31 17:38 UTC, Narflex requested changes

2021-03-31 17:38 UTC, Narflex commented on java/sage/MiniPlayer.java
> +    if(this.mpegSrc.getTranscoder() != null && serverSideTranscoding)
Remove the 'this.' you're using here and other places, it's not needed.

2021-03-31 17:38 UTC, Narflex commented on java/sage/MiniPlayer.java
> +    if(this.mpegSrc.getTranscoder() != null && serverSideTranscoding)
Check if mpegSrc is null before calling a method on it

2021-03-31 17:38 UTC, Narflex commented on java/sage/Seeker.java
> +            if(this.isAClientControllingCaptureDevice(es.capDev) && this.isClientTranscodingMediaFile(es.currRecordFile))
Remove the 'this.' and add a space after the 'if'

2021-03-31 17:38 UTC, Narflex commented on java/sage/Seeker.java
> +	{
Fix the indentation of this block

2021-03-31 17:38 UTC, Narflex commented on java/sage/Seeker.java
> +	  if(this.isAClientControllingCaptureDevice(es.capDev) && this.isClientTranscodingMediaFile(es.currRecordFile))
Same as before

2021-03-31 17:38 UTC, Narflex commented on java/sage/VideoFrame.java
> +      //((MiniPlayer)player).getFi
Remove this line

2021-03-31 17:38 UTC, Narflex commented on java/sage/VideoFrame.java
> +      if(this.getCurrFile() == mf && ((MiniPlayer)player).isTranscoding())
Space after if, remove the 'this.'

2021-04-01 18:46 UTC, jvl711 commented
@Narflex 

I think I addressed all of the issues.  Sorry about the multiple pushes.  Some of the formatting issues were only in Git and not showing in my source.  I was taking a while for me to figure it out.

Thanks,
Josh

2021-04-01 19:27 UTC, merged

2021-04-01 19:27 UTC, Narflex commented
Thanks!